// Shared data — projects + photographer bio.
// Description text intentionally short; reads like a publication contents page.

const BIO = {
  name: "FEDERICA GIGLIO",
  short: "Federica Giglio (b. Milano, IT)",
  long: "Federica Giglio is an Italian photographer based between Los Angeles and Milan. She works across documentary, fine art, editorial, and commercial photography, creating projects in both film and digital formats.",
  location: "LOS ANGELES, CA",
  origin: "MILANO, IT",
  email: "fedegiglio01@gmail.com",
  instagram: "@fede.giglio",
  copyright: "© 2024 — 2026 FEDERICA GIGLIO ALL RIGHTS RESERVED",
};

const PROJECTS = [
  {
    id: "fashion",
    num: "01",
    title: "FASHION",
    year: "2024—2025",
    place: "Milan",
    cat: "Editorial",
    kind: "editorial",
    format: "Film and digital",
    count: 37,
    short: "Commissioned work, editorials, test shoots, and personal projects.",
    long: "Commissioned work, editorials, test shoots, and personal projects.",
    cover: "fashion/cover.png",
    figs: [
      { w:2, h:3, n:"01", src:"fashion/FedericaGiglio_01.jpg" },
      { w:2, h:3, n:"02", src:"fashion/01b.jpg" },
      { w:2, h:3, n:"03", src:"fashion/02b.jpg" },
      { w:2, h:3, n:"04", src:"fashion/03 2.jpg" },
      { w:2, h:3, n:"05", src:"fashion/04.jpg" },
      { w:2, h:3, n:"06", src:"fashion/05.jpg" },
      { w:2, h:3, n:"07", src:"fashion/6.jpg" },
      { w:2, h:3, n:"08", src:"fashion/08.jpg" },
      { w:2, h:3, n:"09", src:"fashion/09.jpg" },
      { w:2, h:3, n:"10", src:"fashion/5 (2).jpg" },
      { w:2, h:3, n:"11", src:"fashion/247_FG_01.jpg" },
      { w:2, h:3, n:"12", src:"fashion/247_FG_12.jpg" },
      { w:2, h:3, n:"13", src:"fashion/amalie_270225_04.jpg" },
      { w:2, h:3, n:"14", src:"fashion/amalie_270225_07.jpg" },
      { w:2, h:3, n:"15", src:"fashion/amalie_270225_12.jpg" },
      { w:2, h:3, n:"16", src:"fashion/amalie_270225_21.png" },
      { w:2, h:3, n:"17", src:"fashion/DevyneEbikake_040325_04.jpg" },
      { w:2, h:3, n:"18", src:"fashion/DevyneEbikake_040325_05.jpg" },
      { w:2, h:3, n:"19", src:"fashion/DevyneEbikake_040325_06.jpg" },
      { w:2, h:3, n:"20", src:"fashion/DevyneEbikake_040325_07.jpg" },
      { w:2, h:3, n:"21", src:"fashion/DevyneEbikake_040325_08.jpg" },
      { w:2, h:3, n:"22", src:"fashion/DevyneEbikake_040325_09.jpg" },
      { w:2, h:3, n:"23", src:"fashion/DevyneEbikake_040325_10.jpg" },
      { w:2, h:3, n:"24", src:"fashion/DevyneEbikake_040325_11.jpg" },
      { w:2, h:3, n:"25", src:"fashion/Giglio_-1.jpg" },
      { w:2, h:3, n:"26", src:"fashion/Giglio_2.jpg" },
      { w:2, h:3, n:"27", src:"fashion/Giglio_3-2.jpg" },
      { w:2, h:3, n:"28", src:"fashion/Giglio_4-2.jpg" },
      { w:2, h:3, n:"29", src:"fashion/Giglio_-2.jpg" },
      { w:2, h:3, n:"30", src:"fashion/Giglio_-3.jpg" },
      { w:2, h:3, n:"31", src:"fashion/Giglio_-4.jpg" },
      { w:2, h:3, n:"32", src:"fashion/Giglio_-5.jpg" },
      { w:2, h:3, n:"33", src:"fashion/Giglio_-6.jpg" },
      { w:2, h:3, n:"34", src:"fashion/Giglio_-7.jpg" },
      { w:2, h:3, n:"35", src:"fashion/Giglio_-8.jpg" },
      { w:2, h:3, n:"36", src:"fashion/Giglio_-9.jpg" },
      { w:2, h:3, n:"37", src:"fashion/Giglio_-16.jpg" },
    ],
  },
  {
    id: "lola",
    num: "02",
    title: "LOLA",
    year: "2024",
    place: "Milan, IT",
    cat: "Editorial",
    kind: "editorial",
    count: 9,
    short: "Editorial.",
    long: "Editorial.",
    cover: "lola/03.jpg",
    localVideo: "lola/lola_raw.mp4",
    figs: [
      { w:2, h:3, n:"01", src:"lola/03.jpg" },
      { w:2, h:3, n:"02", src:"lola/13.jpg" },
      { w:3, h:2, n:"03", src:"lola/16 2.jpg" },
      { w:2, h:3, n:"04", src:"lola/17.jpg" },
      { w:2, h:3, n:"05", src:"lola/18.jpg" },
      { w:2, h:3, n:"06", src:"lola/27.jpg" },
      { w:2, h:3, n:"07", src:"lola/36.jpg" },
      { w:3, h:2, n:"08", src:"lola/49.jpg" },
      { w:2, h:3, n:"09", src:"lola/50.jpg" },
    ],
  },
  {
    id: "postcard-from-nowhere",
    num: "03",
    title: "POSTCARDS FROM NOWHERE",
    year: "2026",
    place: "Los Angeles",
    cat: "Fine Art",
    kind: "diary",
    format: "35mm",
    count: 10,
    short: "At the edge of memory there is a figure. It does not move, it does not speak.",
    long: "At the edge of memory there is a figure.\nIt does not move, it does not speak.\n\nThis is an ongoing body of work about memory, perception and the emotional space between familiarity and distance.",
    cover: "postcard_from_nowhere/cover.png",
    figs: [
      { w:3, h:2, n:"01", src:"postcard_from_nowhere/Giglio_PostcardsFromNowhere-1.jpg" },
      { w:3, h:2, n:"02", src:"postcard_from_nowhere/Giglio_PostcardsFromNowhere-2.jpg" },
      { w:3, h:2, n:"03", src:"postcard_from_nowhere/Giglio_PostcardsFromNowhere-3.jpg" },
      { w:3, h:2, n:"04", src:"postcard_from_nowhere/Giglio_PostcardsFromNowhere-4.jpg" },
      { w:3, h:2, n:"05", src:"postcard_from_nowhere/Giglio_PostcardsFromNowhere-5.jpg" },
      { w:3, h:2, n:"06", src:"postcard_from_nowhere/Giglio_PostcardsFromNowhere-6.jpg" },
      { w:3, h:2, n:"07", src:"postcard_from_nowhere/Giglio_PostcardsFromNowhere-7.jpg" },
      { w:3, h:2, n:"08", src:"postcard_from_nowhere/Giglio_PostcardsFromNowhere-8.jpg" },
      { w:3, h:2, n:"09", src:"postcard_from_nowhere/Giglio_PostcardsFromNowhere-9.jpg" },
      { w:3, h:2, n:"10", src:"postcard_from_nowhere/Giglio_PostcardsFromNowhere-10.jpg" },
    ],
  },
  {
    id: "normandie",
    num: "04",
    title: "NORMANDIE",
    year: "2023",
    place: "Normandie, France",
    cat: "Fine Art",
    kind: "landscape",
    count: 19,
    video: "https://player.vimeo.com/video/1194393864",
    short: "Set along the coast of Normandy, this series reflects on the relationship between body and landscape.",
    long: "Set along the coast of Normandy, this series reflects on the relationship between body and landscape. Moving between intimacy and distance, the photographs explore how presence can reshape the way we experience a place, allowing the landscape to exist as both a physical place and an emotional one.",
    cover: "normandie/04 2.jpg",
    figs: [
      { w:3, h:2, n:"01", src:"normandie/02.jpg" },
      { w:3, h:2, n:"02", src:"normandie/06.jpg" },
      { w:3, h:2, n:"03", src:"normandie/08.1.jpg" },
      { w:3, h:2, n:"04", src:"normandie/04 2.jpg" },
      { w:3, h:2, n:"05", src:"normandie/231126_02.jpg" },
      { w:3, h:2, n:"06", src:"normandie/231126_07.jpg" },
      { w:3, h:2, n:"07", src:"normandie/231126_08.jpg" },
      { w:3, h:2, n:"08", src:"normandie/231129_06.jpg" },
      { w:3, h:2, n:"09", src:"normandie/231129_07.jpg" },
      { w:3, h:2, n:"10", src:"normandie/231201_02.jpg" },
      { w:3, h:2, n:"11", src:"normandie/231201_06.jpg" },
      { w:3, h:2, n:"12", src:"normandie/231202_02.jpg" },
      { w:3, h:2, n:"13", src:"normandie/231202_07.jpg" },
      { w:3, h:2, n:"14", src:"normandie/231202_09_1.jpg" },
      { w:3, h:2, n:"15", src:"normandie/231202_13.jpg" },
      { w:3, h:2, n:"16", src:"normandie/231206_05.jpg" },
      { w:3, h:2, n:"17", src:"normandie/231206_07.jpg" },
      { w:3, h:2, n:"18", src:"normandie/231214_Omh_08.jpg" },
      { w:3, h:2, n:"19", src:"normandie/231214_Beau_04.jpg" },
    ],
  },
  {
    id: "visual-diary",
    num: "05",
    title: "VISUAL DIARY",
    year: "2019—ongoing",
    place: "Various",
    cat: "Diary",
    kind: "diary",
    format: "Film and digital",
    count: 32,
    short: "A collection of work made outside ongoing projects.",
    long: "A collection of work made outside ongoing projects.",
    cover: "visual diary/08 2.jpg",
    figs: [
      { w:3, h:2, n:"01", src:"visual diary/IMG_2913.jpg" },
      { w:2, h:3, n:"02", src:"visual diary/IMG_2463.jpg" },
      { w:2, h:3, n:"03", src:"visual diary/IMG_2468.jpg" },
      { w:2, h:3, n:"04", src:"visual diary/IMG_2476.jpg" },
      { w:3, h:2, n:"05", src:"visual diary/IMG_0791.jpg" },
      { w:2, h:3, n:"06", src:"visual diary/0_01.jpg" },
      { w:2, h:3, n:"07", src:"visual diary/DUNE_01.jpg" },
      { w:2, h:3, n:"08", src:"visual diary/DUNE_02.jpg" },
      { w:2, h:3, n:"09", src:"visual diary/07.jpg" },
      { w:3, h:2, n:"10", src:"visual diary/08 2.jpg" },
      { w:3, h:2, n:"11", src:"visual diary/09 2.jpg" },
      { w:2, h:3, n:"12", src:"visual diary/03 3.jpg" },
      { w:3, h:2, n:"13", src:"visual diary/POST_CASA_SUM23.jpg" },
      { w:2, h:3, n:"14", src:"visual diary/MALTA_09.jpg" },
      { w:2, h:3, n:"15", src:"visual diary/DSC_5331b.jpg" },
      { w:3, h:2, n:"16", src:"visual diary/GreenCar.jpg" },
      { w:3, h:2, n:"17", src:"visual diary/DSC071742.png" },
      { w:3, h:2, n:"18", src:"visual diary/DSC071743.png" },
      { w:3, h:2, n:"19", src:"visual diary/DSC071745.png" },
      { w:3, h:2, n:"20", src:"visual diary/Bythestreet.jpg" },
      { w:3, h:2, n:"21", src:"visual diary/4b.jpg" },
      { w:3, h:2, n:"22", src:"visual diary/10.jpg" },
      { w:3, h:2, n:"23", src:"visual diary/11.jpg" },
      { w:3, h:2, n:"24", src:"visual diary/DSC04162.jpg" },
      { w:3, h:2, n:"25", src:"visual diary/DSC05668-2.jpg" },
      { w:3, h:2, n:"26", src:"visual diary/GiglioF_02_Concept_Term1.jpg" },
      { w:3, h:2, n:"27", src:"visual diary/GiglioF_04_Concept_Term1.jpg" },
      { w:2, h:3, n:"28", src:"visual diary/03c.jpg" },
      { w:3, h:2, n:"29", src:"visual diary/FeGiglio_ColorScheme.jpg" },
      { w:3, h:2, n:"30", src:"visual diary/ThisHouseIsMadeOfSand.jpg" },
      { w:3, h:2, n:"31", src:"visual diary/260329-4x5b.jpg" },
      { w:2, h:3, n:"32", src:"visual diary/timeout.jpg" },
    ],
  },
];

Object.assign(window, { BIO, PROJECTS });
