// Shared data — projects + photographer bio.
// Description text intentionally short; reads like a publication contents page.

const BIO = {
  name: "FEDERICA GIGLIO",
  short: "Federica Giglio (b. Milano, IT)",
  long: "Italian photographer, born in Milano and based in Los Angeles. Her practice centers on the human form — quiet, in-between moments rendered mostly in black & white. The work moves between commissioned fashion editorial, portraiture and the street.",
  location: "LOS ANGELES, CA",
  origin: "MILANO, IT",
  email: "studio@federicagiglio.com",
  phone: "+1 (213) 555 0142",
  instagram: "@federica.giglio",
  copyright: "© 2024 — 2026 FEDERICA GIGLIO ALL RIGHTS RESERVED",
};

const PROJECTS = [
  {
    id: "lola",
    num: "01",
    title: "LOLA",
    year: "2024",
    place: "Los Angeles",
    cat: "Portrait",
    kind: "portrait",
    count: 9,
    short: "A single subject across one summer in Highland Park.",
    long: "LOLA is an extended portrait built across nine afternoons in the same apartment off York Boulevard. The project sits between document and friendship — a record of a person allowing herself to be seen, slowly, in the same light, in the same room, for almost three months.",
    cover: "lola/03.jpg",
    localVideo: "lola/lola_raw.mp4",
    figs: [
      { w:2, h:3, n:"01", src:"lola/03.jpg" },
      { w:2, h:3, n:"02", src:"lola/13.jpg" },
      { w:3, h:2, n:"03", src:"lola/16 2.jpg" },
      { w:2, h:3, n:"04", src:"lola/17.jpg" },
      { w:2, h:3, n:"05", src:"lola/18.jpg" },
      { w:2, h:3, n:"06", src:"lola/27.jpg" },
      { w:2, h:3, n:"07", src:"lola/36.jpg" },
      { w:3, h:2, n:"08", src:"lola/49.jpg" },
      { w:2, h:3, n:"09", src:"lola/50.jpg" },
    ],
  },
  {
    id: "personal-archive",
    num: "02",
    title: "PERSONAL ARCHIVE",
    year: "2019—2024",
    place: "Milano / Los Angeles",
    cat: "Diary",
    kind: "diary",
    count: 27,
    short: "Five years of negatives, contact sheets, screenshots and notes.",
    long: "An open-ended diary kept across two cities. Most frames are unposed and unfinished — they exist to remember a face, a room, a piece of light. Reorganised and re-sequenced each year.",
    cover: "personal_archive/08 2.jpg",
    figs: [
      { w:3, h:2, n:"01", src:"personal_archive/IMG_2913.jpg" },
      { w:2, h:3, n:"02", src:"personal_archive/IMG_2463.jpg" },
      { w:2, h:3, n:"03", src:"personal_archive/IMG_2468.jpg" },
      { w:2, h:3, n:"04", src:"personal_archive/IMG_2476.jpg" },
      { w:2, h:3, n:"05", src:"personal_archive/247_FG_01.jpg" },
      { w:3, h:2, n:"06", src:"personal_archive/IMG_0791.jpg" },
      { w:2, h:3, n:"07", src:"personal_archive/0_01.jpg" },
      { w:2, h:3, n:"08", src:"personal_archive/DUNE_01.jpg" },
      { w:2, h:3, n:"09", src:"personal_archive/DUNE_02.jpg" },
      { w:2, h:3, n:"10", src:"personal_archive/07.jpg" },
      { w:3, h:2, n:"11", src:"personal_archive/08 2.jpg" },
      { w:3, h:2, n:"12", src:"personal_archive/09 2.jpg" },
      { w:2, h:3, n:"13", src:"personal_archive/03 3.jpg" },
      { w:3, h:2, n:"14", src:"personal_archive/POST_CASA_SUM23.jpg" },
      { w:2, h:3, n:"15", src:"personal_archive/247_FG_12.jpg" },
      { w:2, h:3, n:"16", src:"personal_archive/MALTA_09.jpg" },
      { w:2, h:3, n:"17", src:"personal_archive/03 2.jpg" },
      { w:1, h:1, n:"18", src:"personal_archive/bythemoon.jpg" },
      { w:2, h:3, n:"19", src:"personal_archive/timeout.jpg" },
      { w:3, h:2, n:"20", src:"personal_archive/260329-4x5b.jpg" },
      { w:3, h:2, n:"21", src:"personal_archive/ThisHouseIsMadeOfSand.jpg" },
      { w:2, h:3, n:"22", src:"personal_archive/03c.jpg" },
      { w:2, h:3, n:"23", src:"personal_archive/DSC_5331b.jpg" },
      { w:2, h:3, n:"24", src:"personal_archive/FeGiglio_TLE_01.jpg" },
      { w:2, h:3, n:"25", src:"personal_archive/FeGiglio_TLE_02bw.jpg" },
      { w:2, h:3, n:"26", src:"personal_archive/FeGiglio_TLE_03.jpg" },
      { w:2, h:3, n:"27", src:"personal_archive/GiglioF_04_Concept_Term1.jpg" },
    ],
  },
  {
    id: "fashion",
    num: "03",
    title: "FASHION",
    year: "2023",
    place: "Paris / Milano",
    cat: "Editorial",
    kind: "editorial",
    count: 13,
    short: "Selected editorial commissions for independent magazines.",
    long: "A grouping of editorial work shot for independent publications over a single season. Selected images for SSAW Magazine, Replica Man and Mira Mira.",
    cover: "fashion/5 (2).jpg",
    figs: [
      { w:2, h:3, n:"01", src:"fashion/FedericaGiglio_01.jpg" },
      { w:2, h:3, n:"02", src:"fashion/01b.jpg" },
      { w:2, h:3, n:"03", src:"fashion/02b.jpg" },
      { w:2, h:3, n:"04", src:"fashion/04.jpg" },
      { w:2, h:3, n:"05", src:"fashion/05.jpg" },
      { w:2, h:3, n:"06", src:"fashion/6.jpg" },
      { w:2, h:3, n:"07", src:"fashion/08.jpg" },
      { w:2, h:3, n:"08", src:"fashion/09.jpg" },
      { w:2, h:3, n:"09", src:"fashion/5 (2).jpg" },
      { w:2, h:3, n:"10", src:"fashion/amalie_270225_04.jpg" },
      { w:2, h:3, n:"11", src:"fashion/amalie_270225_07.jpg" },
      { w:2, h:3, n:"12", src:"fashion/amalie_270225_12.jpg" },
      { w:2, h:3, n:"13", src:"fashion/amalie_270225_21.png" },
    ],
  },
  {
    id: "devyne",
    num: "04",
    title: "DEVYNE",
    year: "2025",
    place: "Los Angeles",
    cat: "Portrait",
    kind: "portrait",
    count: 8,
    short: "One subject, one session — eight frames.",
    long: "Eight portraits of Devyne Ebikake made in a single afternoon. The session moves between stillness and ease — a study in presence and light.",
    cover: "devyne/DevyneEbikake_040325_07.jpg",
    figs: [
      { w:2, h:3, n:"01", src:"devyne/DevyneEbikake_040325_04.jpg" },
      { w:2, h:3, n:"02", src:"devyne/DevyneEbikake_040325_05.jpg" },
      { w:2, h:3, n:"03", src:"devyne/DevyneEbikake_040325_06.jpg" },
      { w:2, h:3, n:"04", src:"devyne/DevyneEbikake_040325_07.jpg" },
      { w:2, h:3, n:"05", src:"devyne/DevyneEbikake_040325_08.jpg" },
      { w:2, h:3, n:"06", src:"devyne/DevyneEbikake_040325_09.jpg" },
      { w:2, h:3, n:"07", src:"devyne/DevyneEbikake_040325_10.jpg" },
      { w:2, h:3, n:"08", src:"devyne/DevyneEbikake_040325_11.jpg" },
    ],
  },
  {
    id: "normandie",
    num: "05",
    title: "NORMANDIE",
    year: "2022",
    place: "Étretat, FR",
    cat: "Landscape",
    kind: "landscape",
    count: 19,
    video: "https://player.vimeo.com/video/1194393864",
    short: "Three days on the coast, mostly weather.",
    long: "Nineteen frames made on a quiet trip to the Normandy coast. The work was the weather, the cliffs, two friends and the small hotel where we waited out the rain.",
    cover: "normandie/04 2.jpg",
    figs: [
      { w:3, h:2, n:"01", src:"normandie/02.jpg" },
      { w:3, h:2, n:"02", src:"normandie/06.jpg" },
      { w:3, h:2, n:"03", src:"normandie/08.1.jpg" },
      { w:3, h:2, n:"04", src:"normandie/04 2.jpg" },
      { w:3, h:2, n:"05", src:"normandie/231126_02.jpg" },
      { w:3, h:2, n:"06", src:"normandie/231126_07.jpg" },
      { w:3, h:2, n:"07", src:"normandie/231126_08.jpg" },
      { w:3, h:2, n:"08", src:"normandie/231129_06.jpg" },
      { w:3, h:2, n:"09", src:"normandie/231129_07.jpg" },
      { w:3, h:2, n:"10", src:"normandie/231201_02.jpg" },
      { w:3, h:2, n:"11", src:"normandie/231201_06.jpg" },
      { w:3, h:2, n:"12", src:"normandie/231202_02.jpg" },
      { w:3, h:2, n:"13", src:"normandie/231202_07.jpg" },
      { w:3, h:2, n:"14", src:"normandie/231202_09_1.jpg" },
      { w:3, h:2, n:"15", src:"normandie/231202_13.jpg" },
      { w:3, h:2, n:"16", src:"normandie/231206_05.jpg" },
      { w:3, h:2, n:"17", src:"normandie/231206_07.jpg" },
      { w:3, h:2, n:"18", src:"normandie/231214_Omh_08.jpg" },
      { w:3, h:2, n:"19", src:"normandie/231214_Beau_04.jpg" },
    ],
  },
  {
    id: "streets",
    num: "06",
    title: "STREETS",
    year: "2021—2024",
    place: "Various",
    cat: "Street",
    kind: "street",
    count: 16,
    short: "Strangers, walking. Milano, LA, Tokyo, Marseille.",
    long: "An ongoing collection of unposed frames made on the move. Sequenced by colour and pace, not by city.",
    cover: "street/GreenCar.jpg",
    figs: [
      { w:3, h:2, n:"01", src:"street/GreenCar.jpg" },
      { w:3, h:2, n:"02", src:"street/DSC071742.png" },
      { w:3, h:2, n:"03", src:"street/DSC071743.png" },
      { w:3, h:2, n:"04", src:"street/DSC071744.png" },
      { w:3, h:2, n:"05", src:"street/DSC071745.png" },
      { w:3, h:2, n:"06", src:"street/DSC071746.png" },
      { w:3, h:2, n:"07", src:"street/FeGiglio_ColorScheme.jpg" },
      { w:3, h:2, n:"08", src:"street/Bythestreet.jpg" },
      { w:3, h:2, n:"09", src:"street/4b.jpg" },
      { w:3, h:2, n:"10", src:"street/10.jpg" },
      { w:3, h:2, n:"11", src:"street/11.jpg" },
      { w:3, h:2, n:"12", src:"street/DSC04162.jpg" },
      { w:3, h:2, n:"13", src:"street/DSC05668-2.jpg" },
      { w:3, h:2, n:"14", src:"street/DSC071742 copia.jpg" },
      { w:3, h:2, n:"15", src:"street/FeGiglio_TLE_05.jpg" },
      { w:3, h:2, n:"16", src:"street/GiglioF_02_Concept_Term1.jpg" },
    ],
  },
];

Object.assign(window, { BIO, PROJECTS });
